### ISSUE TITLE
Issue in accruing UBI

### ISSUE THREAD

**Issue by wimmaeyens** [Proof-Of-Humanity/proof-of-humanity-web#188]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/81929858/113520126-4841cb00-9591-11eb-9e1a-d24863cb7c7a.png)

Hey all, 

I am registered as a human. After verification of my account I would like to start accruing UBI. I have clicked the foreseen link several times and paid the transaction fee, but it keeps on resetting;

Anything you can do to help resolve this situation?

Thanks in advance, 

Wim 

0xf073373a1c3a96e6b1d12f64cd1f4ee317e842b8

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Device and Browser Information**

**Comment by mtsalenc** [comment]
Hey Wim, can you please give us the transaction hash of one of the  transaction you sent to start accruing UBI?

**Comment by wimmaeyens** [comment]
Hi! 

Here is the transaction ID: 0xf652847bb6e36789d5180226e6db739030bb8ae407dff6c41e06313401a01eff
Thanks in advance!
Here are some others as well should this help you forward :)
0x55735ce46b8159a678aeece41b090a7795c7150319c42b703b00327c3de7cd81
0x76a71d96ac13226c7a23bae9ff4237f9e9d33769d2c634ac3df758c9ee31e245

**Comment by wimmaeyens** [comment]
Hey, 

Did you manage to have a look at the above? 
I see the button "Start accruing" resets after a while, but I see the problem keeps on re-occuring unfortunately.

Cheers
Wim

**Comment by mtsalenc** [comment]
None of your transactions were ever included in a block (probably due to a spike in gas prices):

https://etherscan.io/tx/0xf652847bb6e36789d5180226e6db739030bb8ae407dff6c41e06313401a01eff
https://etherscan.io/tx/0x55735ce46b8159a678aeece41b090a7795c7150319c42b703b00327c3de7cd81
https://etherscan.io/tx/0x76a71d96ac13226c7a23bae9ff4237f9e9d33769d2c634ac3df758c9ee31e245

You will only start accruing if the transaction is picked up by a miner and included in a block.

To fix the issue, do the same thing but make sure to use a gas price high enough that your transaction gets included in a block.

**Comment by wimmaeyens** [comment]
Fixed it! Thanks for your help on this :)
