### ISSUE TITLE
The number of profiles displayed show the amount displayed on the page not the total amount

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#2]
![image](https://user-images.githubusercontent.com/8873352/106512532-a686fa80-64c9-11eb-8c5e-293797345845.png)

**Comment by epiqueras** [comment]
Having a total counter will be hard for the same reason it was hard to do in the contract, submissions expire, and the expiration times can be changed by governance.

Do you think there is a better way of doing it than fetching the submission times of all submissions and computing the total using the current contract duration parameters?

**Comment by clesaege** [comment]
Can't we do that with the graph?
Otherwise just showing the number of submissions (https://github.com/Proof-Of-Humanity/Proof-Of-Humanity/blob/master/contracts/ProofOfHumanity.sol#L145) would be a better indicator.

**Comment by epiqueras** [comment]
We can, but it will still be slow when the number of submissions gets big if we do it dynamically. If we cache it, we would need to update it whenever the contract duration parameters change. We wouldn't be able to do that in the subgraph because it would require looping over all the submissions, making the mapping time out. We would have to do it in another service.

>Otherwise just showing the number of submissions

I think that's a better idea for now. It's also nice to see that stat.

The update is building now.
