### ISSUE TITLE
Wrong UBI balance

### ISSUE THREAD

**Issue by mtsalenc** [Proof-Of-Humanity/proof-of-humanity-web#281]
**Describe the Bug**
Wrong UBI balance being displayed in the user's profile;

**To Reproduce**
Compare the balance displayed by visiting:
https://app.proofofhumanity.id/profile/0x245Bd6B5D8f494df8256Ae44737A1e5D59769aB4?network=mainnet
with the one returned by calling `balanceOf` in the the UBI contract:
https://etherscan.io/token/0xdd1ad9a21ce722c151a836373babe42c868ce9a4?a=0x245Bd6B5D8f494df8256Ae44737A1e5D59769aB4#readProxyContract

**Comment by alcercu** [comment]
I believe this occurs because the amount displayed on the web is the amount of UBI accrued by the account, calculated using `accruedSince` and `accruedPerSecond`, not their actual balance. We could change the wording to something like "Accrued UBI", or actually querying `balanceOf` to get the correct account balance. What do you think?

**Comment by mtsalenc** [comment]
Yes, I'll pick this one up and change it to actually query `balanceOf`
