### ISSUE TITLE
Profile shows Removed instead of Pending Registration

### ISSUE THREAD

**Issue by NingF23** [Proof-Of-Humanity/proof-of-humanity-web#294]
**Describe the Bug**
I'm helping my girlfriend on the registration process and I already vouched her. But right now we have a bizarre bug: when the challeging period finished, from my phone with my profile logged in I selected start accruing on her profile (because she didn't have enough funds).
The gas was very very high (300-400 usd), so I tried to limit the max amout of gas of the transaction.
First transaction: failed, not enough gas.
Second transaction: failed, again.
Ok, that's a good way to learn about gas fees and variables.
The problem is: after those two failed transactions, *her profile is now Removed*. It took 2 minutes after the second transaction terminated.
No one requested the removal.
I just copy here her profile and the two transactions. It looks something went wrong here.
Profile:
https://app.proofofhumanity.id/profile/0x8Bac49945bCd11bDB3c34b8339C4121Bf2baFdbd
Tx1:
https://etherscan.io/tx/0x00b2adeaad56109e096cf54c1d3bb01688feb787ddd163e8db4a8d02e3b6f974
Tx2:
https://etherscan.io/tx/0x9499756be1b3412bb70747be6115d10c20484de4502ba28ec652d6597151f339

**Expected Behavior**
Should have been in Pending Registration

**Device and Browser Information**
All device and browser

**Comment by fnanni-0** [comment]
Root cause: https://github.com/graphprotocol/graph-node/issues/2409.

@NingF23 Until the graph bug is fix or until the UI handles this bug, users having this issue can interact directly with the contract on etherscan. They would have to go [here](https://etherscan.io/address/0xC5E9dDebb09Cd64DfaCab4011A0D5cEDaf7c9BDb#writeContract) and call `15. executeRequest` using their address in the `_submissionID` field.

**Comment by lbonini** [comment]
I confirm the the step described by @fnanni-0 worked. After that, the button "start accruing" showed on the UI. So I continue with the regular procedure and it worked fine.
Thank you,
