### ISSUE TITLE
profile stuck on vouching phase

### ISSUE THREAD

**Issue by estebald** [Proof-Of-Humanity/proof-of-humanity-web#297]
**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Device and Browser Information**

**Comment by estebald** [comment]
Profile stuck on vouching phase:
https://app.proofofhumanity.id/profile/0xf34cf11df1d76f35cc3c73632c92485d0084df7d
Please fix the issue.

**Comment by felixgabathuler** [comment]
My profile is also stuck on vouching phase: 
https://app.proofofhumanity.id/profile/0x24609303b67051ef77735e34d671e2a13e3da35d

The finalize registration and start accruing button keeps spinning, not able to click on it

**Comment by mtsalenc** [comment]
@estebald this is not something we can fix, your profile is stuck because your voucher also vouched for someone else. Vouches are processed one at a time. Anyway we added a notice to avoid confusion.

@felixgabathuler It is loading because the transaction you submitted was not mined yet due to low gas prices. Please try again with a higher gas price or wait for usage to drop.
