### ISSUE TITLE
Sometimes when changing the page number, the cards keeps loading and buttons to change pages dissapear

### ISSUE THREAD

**Issue by clesaege** [Proof-Of-Humanity/proof-of-humanity-web#3]
![image](https://user-images.githubusercontent.com/8873352/106513034-4e042d00-64ca-11eb-8a04-088b5c4a620a.png)

I got the issue on chrome.

**Comment by epiqueras** [comment]
Hi @morrys, I hope you're doing great.

We're running into this issue when using `loadQuery` on version `3.7.0` of `relay-hooks`.

Specifically when things happen in this order:

- `prefetch.next(environment, queries[path], query)` gets called with `queries[path]` 1, and `query` 1.
- `prefetch.next(environment, queries[path], query)` gets called with `queries[path]` 2, and `query` 2.
- `prefetch.next(environment, queries[path], query)` gets called with `queries[path]` 1, and `query` 1.
- `prefetch.next(environment, queries[path], query)` gets called with `queries[path]` 1, and `query` 3.

In the app, this happens when:

- You load the first page.
- You navigate to a specific profile.
- You navigate back to the first page.
- You paginate to the second page.

After that last call with the first query, but new variables, I see the network responds correctly, but `relay-hooks` returns `null` and never updates.

Any idea what might be going on?

**Comment by morrys** [comment]
hi @epiqueras & @clesaege,
i just created a PR that solves the problem in version 4.0.0 👍 
Soon I intend to officially release the 4.1.0 release with this fix too.

At the moment I prefer not to keep version 3.x active even if in the PR I put a comment how to solve the problem in version 3.7.0

**Comment by epiqueras** [comment]
Thanks, @morrys, that's super helpful.

I did try version `4.0.0` before opening this, and I found many other issues. Do you think it would be possible to backport the fix and release `3.7.1`?

**Comment by morrys** [comment]
What kind of issue? I tried it and i just had to edit the useQuery in these files:
![immagine](https://user-images.githubusercontent.com/2670647/106635002-9f6ef380-6580-11eb-930f-d6e8f0ead1cc.png)

**Comment by morrys** [comment]
I think that the problem is related to the same PR

**Comment by morrys** [comment]
@epiqueras, your feedback on the version of relay hook currently on the master (4.1.0) would be very helpful.

so, if there are any problems I can help you investigate before officially releasing it 👍

**Comment by epiqueras** [comment]
@morrys, when can you release a beta so that I can test it?

**Comment by epiqueras** [comment]
@morrys, the fix you described here relay-tools/relay-hooks/pull/154 for `v3.7.0` works perfectly.

I tried version 4, but it's slowing the app down a lot, and being this close to a release, I prefer to be safe with a `v3.7.1`.

I've forked the repo and patched it myself so that it works until you have time for cutting a new release.

Thanks so much for the quick and accurate help :smile:

**Comment by morrys** [comment]
Small update:
the problem was caused by the incompatibility between relay-hooks 4 and relay-runtime 10.0.1.

To use relay-hooks 4.x you need to have:
"peerDependencies": {
     "react": "^ 16.9.0 || ^ 17",
     "relay-runtime": "> = 10.1.0"
   },
