### ISSUE TITLE
Vouching Phase Eternal

### ISSUE THREAD

**Issue by Gabrieltropea** [Proof-Of-Humanity/proof-of-humanity-web#305]
I opened this bug because I don't know if there is a problem with my profile or it's just a matter of time, since the last change in my profile was more than a month ago and I'm still in "Vouching Phase", when people who register now, have their profile validated in a week at the most.
Please let me know if there is any problem or I have to update something, thank you very much.

https://app.proofofhumanity.id/profile/0xe8bd596f91f8d1d2c08d2fa161bc17e03f4a7c9e

**Comment by fnanni-0** [comment]
In order to get to the next phase you need a vouch from someone who is already registered in Proof of Humanity. You might be interested in reading these: https://kleros.gitbook.io/docs/products/proof-of-humanity and https://blog.kleros.io/proof-of-humanity-an-explainer/.

If you don't know anyone who is already registered in POH, there are telegram groups that help with this. You can ask about it in the official POH telegram group.

**Comment by mtsalenc** [comment]
Closing this as it is not an a bug report.
