### ISSUE TITLE
Submission of evidence after challenge

### ISSUE THREAD

**Issue by HenruCivi** [Proof-Of-Humanity/proof-of-humanity-web#317]
I'm not been able to submit evidence for a challenge (tried during a whole day and it was impossible)

**Comment by mtsalenc** [comment]
We need more details to resolve this issue:
- A link to the profile you are trying to submit evidence
- What happened? Is the transaction reverting? Do you get a popup? Did you manage to submit the transaction at all?

**Comment by HenruCivi** [comment]
Hi, thanks for the quick response:

- Link to my profile: https://app.proofofhumanity.id/profile/0xb48413D7D48c154bEBb9EAB8C570d3a7Fc1D30fb
- The transaction is freezed in "Preparing the transaction" (after financing it via metamask), so i'm not been able to submit evidence and get my profile approved (after already been vouched) 
![image](https://user-images.githubusercontent.com/84352675/118563754-8b24c000-b745-11eb-8ae3-dfc1341ce6eb.png)

**Comment by mtsalenc** [comment]
Do you happen to be using WalletConnect? If so, please use metamask on your desktop browser directly (make sure to follow the link from [https://metamask.io](https://metamask.io) to avoid phishing). 
Users have been reporting that WalletConnect has been slow occasionally for some reason (to the point of the transaction never arriving on your smartphone).

**Comment by HenruCivi** [comment]
No, I did not use WalletConnect. I have been using always metamask from my desktop browser directly.

**Comment by mtsalenc** [comment]
What browser are you using?

**Comment by HenruCivi** [comment]
Chrome

**Comment by mtsalenc** [comment]
Can you please try with Firefox + Metamask?

**Comment by HenruCivi** [comment]
No luck unfortunately

**Comment by HenruCivi** [comment]
Hi, I'm still unable to submit the evidence and only have one day left until the challenge deadline for my registration.
Would you please kindly help me? I'm attaching the evidence here in case is useful.

https://user-images.githubusercontent.com/84352675/118713601-8240f680-b7f8-11eb-86cb-bb29ac84c038.mp4

**Comment by mtsalenc** [comment]
> only have one day left until the challenge deadline for my registration.
Please disregard that information in the UI, since the submission was already challenged it is meaningless. What matters now is the dispute resolution process which you can follow by clicking the dispute number or going here: https://court.kleros.io/cases/729. Note that the submission is in the evidence period (current deadline is in 4 days) but you will still be able to submit evidence until the dispute resolves.

> The transaction is freezed in "Preparing the transaction" (after financing it via metamask), so i'm not been able to submit evidence and get my profile approved (after already been vouched)
If I understand correctly, the transaction was submitted but likely was never mined. I was not able to reproduce any errors locally and my wallet correctly prompts me for a signature;

Please, lets chat directly to speed up this support. Reach out to me on this channel: https://t.me/pohDebug
