### ISSUE TITLE
Pending Vouch Release

### ISSUE THREAD

**Issue by n1c0rn10** [Proof-Of-Humanity/proof-of-humanity-web#320]
I Vouched for my brother and he made a mistake in his profile (I didn´t check) and was challenged. He lost and he generated his profile again. Now we checked that the profile its OK and comply with all the rules. I vouched again for him but the following message appears: "All vouches given to this submission are being used by other submissions. Either wait for them to resolve or ask that someone else with a free vouch to also vouch for you." 
The thing is I haven't vouched for anyone else but my ability to vouch its steel unresolved/pending. I vouched 2 times for the same person but it seems I was not processed and the second time keeps waiting for the first time to be resolved.

Profile from my brother:
https://app.proofofhumanity.id/profile/0xf322ffe78add540e30b74d3e738d3aca28659931

They have assigned a new person in the crowd vouching group and same thing happens with his profile.
Profile from crowdvouching:
https://app.proofofhumanity.id/profile/0x310D36b666549D99E086982DB2fB4517C9eF4312
What can I do?

**Comment by mtsalenc** [comment]
Thank you for taking the time to report:
Regarding your brother's profile: The message is correct, your vouch is being used in this profile: https://app.proofofhumanity.id/profile/0x310d36b666549d99e086982db2fb4517c9ef4312, so you need to wait for that request to resolve for it to be available for your brother.

Actually, I just noticed that is the same profile you mentioned below. Since radu's vouch seems free, I'd ask that he vouch for your brother (after checking his profile), that way both would move forward.

Regarding weirdness with resubmitted profiles, there was an issue that was fixed last week so we should not see any more cases like that, but if you do see or see someone reporting, please reopen this issue with the profile.

**Comment by mtsalenc** [comment]
Also regarding the weirdness with both profiles taking a long time to be processed: there was a bug in the vouching system that was fixed monday (https://github.com/Proof-Of-Humanity/vouch-db/commit/0394f95310d0e10af779ed818f28a8c95b36b628).

We should not see anymore reapply stuck cases but if you do, please reopen this issue with the profile.
